-- begin FINZPIX_USUARIOS
create unique index IDX_FINZPIX_USUARIOS_UNQ on FINZPIX_USUARIOS (ID) where DELETE_TS is null ^
create unique index IDX_FINZPIX_USUARIOS_UK_NOMBRE on FINZPIX_USUARIOS (NOMBRE) where DELETE_TS is null ^
-- end FINZPIX_USUARIOS
-- begin FINZPIX_EGRESO
alter table FINZPIX_EGRESO add constraint FK_FINZPIX_EGRESO_ON_TIPO foreign key (TIPO_ID) references FINZPIX_TIPO_EGRESOS(ID)^
alter table FINZPIX_EGRESO add constraint FK_FINZPIX_EGRESO_ON_USUARIO foreign key (USUARIO_ID) references FINZPIX_USUARIOS(ID)^
create unique index IDX_FINZPIX_EGRESO_UNQ on FINZPIX_EGRESO (ID) where DELETE_TS is null ^
create index IDX_FINZPIX_EGRESO_ON_TIPO on FINZPIX_EGRESO (TIPO_ID)^
create index IDX_FINZPIX_EGRESO_ON_USUARIO on FINZPIX_EGRESO (USUARIO_ID)^
-- end FINZPIX_EGRESO
-- begin FINZPIX_BALANCE
create unique index IDX_FINZPIX_BALANCE_UNQ on FINZPIX_BALANCE (ID) where DELETE_TS is null ^
-- end FINZPIX_BALANCE
-- begin FINZPIX_INGRESOS
alter table FINZPIX_INGRESOS add constraint FK_FINZPIX_INGRESOS_ON_USUARIO foreign key (USUARIO_ID) references FINZPIX_USUARIOS(ID)^
create unique index IDX_FINZPIX_INGRESOS_UNQ on FINZPIX_INGRESOS (ID) where DELETE_TS is null ^
create index IDX_FINZPIX_INGRESOS_ON_USUARIO on FINZPIX_INGRESOS (USUARIO_ID)^
-- end FINZPIX_INGRESOS
-- begin FINZPIX_TIPO_EGRESOS
alter table FINZPIX_TIPO_EGRESOS add constraint FK_FINZPIX_TIPO_EGRESOS_ON_CATEGORIA foreign key (CATEGORIA_ID) references FINZPIX_CATEGORIA_EGRESOS(ID)^
create unique index IDX_FINZPIX_TIPO__EGRESOS_UNQ on FINZPIX_TIPO_EGRESOS (ID) where DELETE_TS is null ^
create unique index IDX_FINZPIX_TIPO__EGRESOS_UNQ_1 on FINZPIX_TIPO_EGRESOS (CATEGORIA_ID) where DELETE_TS is null ^
create unique index IDX_FINZPIX_TIPO_EGRESOS_UK_TIPO on FINZPIX_TIPO_EGRESOS (TIPO) where DELETE_TS is null ^
create index IDX_FINZPIX_TIPO_EGRESOS_ON_CATEGORIA on FINZPIX_TIPO_EGRESOS (CATEGORIA_ID)^
-- end FINZPIX_TIPO_EGRESOS
-- begin FINZPIX_CATEGORIA_EGRESOS
create unique index IDX_FINZPIX_CATEGORIA__EGRESOS_UNQ on FINZPIX_CATEGORIA_EGRESOS (ID) where DELETE_TS is null ^
create unique index IDX_FINZPIX_CATEGORIA_EGRESOS_UK_CATEGORIA on FINZPIX_CATEGORIA_EGRESOS (CATEGORIA) where DELETE_TS is null ^
-- end FINZPIX_CATEGORIA_EGRESOS
