alter table FINZPIX_EGRESO add constraint FK_FINZPIX_EGRESO_ON_TIPO foreign key (TIPO_ID) references FINZPIX_TIPO_EGRESOS(ID);
alter table FINZPIX_EGRESO add constraint FK_FINZPIX_EGRESO_ON_USUARIO foreign key (USUARIO_ID) references FINZPIX_USUARIOS(ID);
create unique index IDX_FINZPIX_EGRESO_UNQ on FINZPIX_EGRESO (ID) where DELETE_TS is null ;
create index IDX_FINZPIX_EGRESO_ON_TIPO on FINZPIX_EGRESO (TIPO_ID);
create index IDX_FINZPIX_EGRESO_ON_USUARIO on FINZPIX_EGRESO (USUARIO_ID);
