alter table FINZPIX_INGRESOS add constraint FK_FINZPIX_INGRESOS_ON_USUARIO foreign key (USUARIO_ID) references FINZPIX_USUARIOS(ID);
create unique index IDX_FINZPIX_INGRESOS_UNQ on FINZPIX_INGRESOS (ID) where DELETE_TS is null ;
create index IDX_FINZPIX_INGRESOS_ON_USUARIO on FINZPIX_INGRESOS (USUARIO_ID);
