alter table FINZPIX_TIPO_EGRESOS add constraint FK_FINZPIX_TIPO_EGRESOS_ON_CATEGORIA foreign key (CATEGORIA_ID) references FINZPIX_CATEGORIA_EGRESOS(ID);
create index IDX_FINZPIX_TIPO_EGRESOS_ON_CATEGORIA on FINZPIX_TIPO_EGRESOS (CATEGORIA_ID);
