create unique index IDX_FINZPIX_CATEGORIA__EGRESOS_UNQ on FINZPIX_CATEGORIA_EGRESOS (ID) where DELETE_TS is null ;
create unique index IDX_FINZPIX_CATEGORIA_EGRESOS_UK_CATEGORIA on FINZPIX_CATEGORIA_EGRESOS (CATEGORIA) where DELETE_TS is null ;
